### ISSUE TITLE
read access violation in microprofile.cpp:3828

### ISSUE THREAD

**Issue by ands** [jonasmr/microprofile#16] opened 2017-06-24 22:15 UTC
Hey,

this project looks very useful, thanks for making it! :)
I'm trying microprofile for the first time and I'm always getting a read access violation (see title) as soon as I try to capture frames using the capture button in the live view.
I'm testing this with the noui_vulkan demo running with VS2015 on Windows 8.1.
It doesn't crash if I go to 127.0.0.1:1338/30 directly, but it also does not display any data.
I'm not sure how to actually use microprofile yet, but it looks like I can currently not get any capture data out of the demo app...
Am I missing something?

Thank you.

**Comment by ands** [comment] 2017-06-24 22:23
Short update: Capturing data on the "noui" example does actually work with the same setup :)

**Comment by jonasmr** [comment] 2017-06-25 07:50
Hi.

It sounds like you're using it just as intended :)
I've reproduced the bug, and will have a look at it asap.

**Comment by jonasmr** [comment] 2017-06-25 09:22
fixed in e472f5e6d6373f760347a0d0e80de021716eac20

**Closed** 2017-06-25 09:22 UTC

**Comment by ands** [comment] 2017-06-25 13:06
Cool. Thanks a lot! :) I now started using microprofile on an OpenGL app and it is a great tool. I really like to work with it!

**Comment by jonasmr** [comment] 2017-06-25 15:33
Thanks, I'm glad you like it :)
